---
- hosts: all
  tasks:

  - name: install dependencies
    become: true
    package: {name: "{{item}}", state: latest}
    with_items: [curl, libselinux-python]
  - name: install base terminal
    become: true
    package: {name: "{{item}}", state: latest}
    with_items: [zsh, tmux, emacs-nox]

  - name: online install oh-my-zsh
    environment: {SHELL: /bin/zsh} # fake the fact we're already in zsh
    shell: sh -c "$(curl -fsSL https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh)"
    args:
      creates: ~/.oh-my-zsh
  - name: set default shell to zsh
    become: true
    user:
      name: "{{ansible_user_id}}"
      shell: /bin/zsh
  - name: template zshrc to my home
    template:
      src: templates/zshrc.j2
      dest: ~/.zshrc
      backup: yes

  - name: online isntall of prelude
    shell: sh -c "$(curl -fsSL https://git.io/epre)"
    args:
      creates: ~/.emacs.d/core/prelude-core.el
      